namespace GruntzUnityverse.Enumz {
  public enum ToolName {
    Barehandz = 0,
    Bomb = 1,
    Boomerang = 2,
    BoxingGlovez = 3,
    Bricklayer = 4,
    Club = 5,
    Gauntletz = 6,
    GooberStraw = 7,
    GravityBootz = 8,
    Gunhat = 9,
    NerfGun = 10,
    Rockz = 11,
    Shield = 12,
    Shovel = 13,
    Spring = 14,
    SpyGear = 15,
    Sword = 16,
    TimeBombz = 17,
    Toob = 18,
    Wand = 19,
    Warpstone = 20,
    WelderKit = 21,
    Wingz = 22,
    None = 23,
  }
}
